### PR TITLE
Switch from file to path for octoprint 1.4

### LINKED ISSUE #8: Plugin uses deprecated field `file` from FileSelected event payload that's going to be removed in 1.4.0
```
2019-12-12 11:49:50,627 - octoprint.plugin - ERROR - Error while calling plugin layerdisplay
Traceback (most recent call last):
  File "C:\Devel\OctoPrint\OctoPrint\src\octoprint\plugin\__init__.py", line 224, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "C:\Devel\OctoPrint\devenv\lib\site-packages\layerdisplay\__init__.py", line 21, in on_event
    self.print_job = PrintJob(payload)
  File "C:\Devel\OctoPrint\devenv\lib\site-packages\layerdisplay\PrintJob.py", line 19, in __init__
    self.file_path = file_selected_payload['file']
KeyError: 'file'
```

Compare to [the docs](http://docs.octoprint.org/en/master/events/index.html#file-handling):

image

See also https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/99 from another plugin, also contains steps to solve.

### PR DESCRIPTION
**Pull request by dshokouhi**
This _should_ fix #8 and #9 

Didn't see `file` referenced elsewhere so I think this should be it.

### CODE REVIEW

**Comment by atomgomba** [comment]
Seems like a plausible change, can this get merged please?

**Comment by aerickson** [comment]
Hmm, I tested this and it's not working.

```
2020-03-23 02:27:15,178 - octoprint.plugin - ERROR - Error while calling plugin layerdisplay
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 224, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 21, in on_event
    self.print_job = PrintJob(payload)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/PrintJob.py", line 22, in __init__
    self.file_size = os.path.getsize(self.file_path)
  File "/home/pi/oprint/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'REDACTED.gcode'


2020-03-23 22:55:53,673 - octoprint.plugin - ERROR - Error while calling plugin layerdisplay
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 224, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 21, in on_event
    self.print_job = PrintJob(payload)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/PrintJob.py", line 24, in __init__
    self.file_size = os.path.getsize(self.file_path)
  File "/home/pi/oprint/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'REDACTED.gcode'

```

Foosel says:
> You should switch that to use path and origin instead and resolve those to the path on disk using self._file_manager.path_on_disk, otherwise your plugin will run into issues with 1.4.0.

Here's the fix from the other project that had a similar issue: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/blob/b5ee4b117a948000e68d12d4808537d570bf4c3c/octoprint_DisplayLayerProgress/__init__.py#L864

I'm working on a PR.

**Comment by aerickson** [comment]
I think I've got it working in #11.

**Comment by dshokouhi** [comment]
closing in favor of #11

**Pull request closed without merging**
